repos:
  - repo: local
    hooks:
      - id: isort
        args: [ '--profile', 'black' ]
        name: isort
        entry: isort --settings-file "/Users/askolenko/PycharmProjects/django-ecommerce-api/.isort.cfg" .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config "/Users/askolenko/PycharmProjects/django-ecommerce-api/.black" .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config "/Users/askolenko/PycharmProjects/django-ecommerce-api/.flake8" .
        language: system
        types: [ python ]
        pass_filenames: false
